# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  non-go = true
  unused-packages = true

[[override]]
  name = "github.com/Sirupsen/logrus"
  source = "github.com/sirupsen/logrus"

[[override]]
  name = "github.com/docker/docker"
  source = "github.com/moby/moby"
  branch = "master"

[[override]]
  name = "github.com/moby/buildkit"
  branch = "master"

[[override]]
  name = "github.com/hanwen/go-fuse"
  revision = "master"

[[override]]
  name = "github.com/grpc-ecosystem/grpc-opentracing"
  revision = "420e5c3331a082e0c873adeeab1819fe1749dd0b"
  source = "github.com/tonistiigi/grpc-opentracing"

[[override]]
  name = "github.com/hashicorp/go-immutable-radix"
  revision = "826af9ccf0feeee615d546d69b11f8e98da8c8f1"
  source = "github.com/tonistiigi/go-immutable-radix"

[[override]]
  name = "github.com/dmcgowan/go-tar"
  branch = "go1.10"

[[constraint]]
  name = "github.com/opencontainers/runc"
  branch = "all-rootless-patches"
  source = "github.com/jessfraz/runc"

[[constraint]]
  name = "github.com/containerd/go-runc"
  branch = "force-mapping-tool"
  source = "github.com/jessfraz/go-runc"

[[override]]
  name = "github.com/opencontainers/runtime-spec"
  version = "v1.0.1"

[[constraint]]
  name = "github.com/containerd/containerd"
  branch = "master"

[[override]]
  name = "github.com/containerd/continuity"
  branch = "master"

[[override]]
  name = "github.com/docker/libnetwork"
  revision = "822e5b59d346b7ad0735df2c8e445e9787320e67"

[[override]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[override]]
  name = "github.com/docker/cli"
  branch = "master"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

[[constraint]]
  name = "github.com/genuinetools/reg"
  branch = "master"

[[constraint]]
  name = "github.com/tonistiigi/fsutil"
  branch = "export-some-functions"
  source = "github.com/jessfraz/fsutil"
